### PR TITLE
Latest changes to Tenable connector

### PR DESCRIPTION
**Pull request by delliott90**
Updated the versions of the CAR framework and pytenable that are used, made a couple of the arguments non-required.

### CODE REVIEW

**Comment by SteveMcGrath** [comment]
What was the bug?  Did you test against 1.4.3?  Did that address it?

**Review by baulus — APPROVED** [review]

**Comment by delliott90** [comment]
@SteveMcGrath We didn't try it with 1.4.3, but with 1.4.2, which was the latest when we implemented this change, we were seeing the following error when running the connector:

Traceback (most recent call last):
  File "/usr/src/app/app.py", line 6, in <module>
    from connector.server_access import AssetServer
  File "/usr/src/app/connector/server_access.py", line 1, in <module>
    from tenable.io import TenableIO
  File "/usr/local/lib/python3.9/site-packages/tenable/io/__init__.py", line 57, in <module>
    from .cs.api import ContainerSecurity
  File "/usr/local/lib/python3.9/site-packages/tenable/io/cs/api.py", line 23, in <module>
    from tenable.io.cs.images import ImagesAPI
  File "/usr/local/lib/python3.9/site-packages/tenable/io/cs/images.py", line 14, in <module>
    from typing_extensions import Literal
ModuleNotFoundError: No module named 'typing_extensions'

**Comment by SteveMcGrath** [comment]
we had identified that issue, corrected it, and added testing to ensure that doesn't happen again.  I do agree hard-linking to a lib version makes sense, however can you please test with 1.4.3?

**Comment by baulus** [comment]
We tested the connector against 1.4.2, which was the latest version on Dec 6th, on the day we found and fixed this issue. Since 1.4.2 had a problem (appearing on Linux, though it was ok when testing on mac) we used the one that we were sure is ok both on mac and Linux, 1.2.8.

**Comment by baulus** [comment]
Tested with 1.4.3 in both mac and linux. Works without issue.

**Review by baulus — APPROVED** [review]

**Pull request merged**
